version: '3'
services:
  mysql:
    restart: always
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  #    MYSQL_ROOT_HOST: '%'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

    ports:
      - "3323:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root--execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

  inventry-sys:
    restart: on-failure
    build: ./
    ports:
      - 8086:8086
 #   environment:
 #     WAIT_HOSTS: mysql:3306
    depends_on:
      - mysql