FROM openjdk:8-alpine
COPY ./target/InventoryManagementSystem-0.0.1-SNAPSHOT.jar /usr/src/InventoryManagementSystem.jar
WORKDIR /usr/src
#EXPOSE 8085:8085
CMD ["java", "-jar", "InventoryManagementSystem.jar"]
