node {
    stage 'Clone the project'
    git 'https://github.com/pacegiffgaff/Sandeep_Prakash_Code_Repo.git'

    dir('SpringBootTddApplication') {
        stage("Compilation") {

                if (isUnix()) {
                    sh "./mvnw clean install -DskipTests"
                } else {
                    bat "./mvnw.cmd clean install -DskipTests"
                }

        }

        stage("Tests and Deployment") {
            parallel 'Unit tests': {
                stage("Running unit tests") {
                    try {
                        if (isUnix()) {
                            sh "./mvnw test -Punit"
                        } else {
                            bat "./mvnw.cmd test -Punit"
                        }
                    } catch(err) {
                        throw err
                    }

                }
            }, 'Integration tests': {
                stage("Running integration tests") {
                    try {
                        if (isUnix()) {
                            sh "./mvnw test -Pintegration"
                        } else {
                            bat "./mvnw.cmd test -Pintegration"
                        }
                    } catch(err) {
                        throw err
                    }
                }
            }

            stage("Staging") {
                if (isUnix()) {
                    sh "pid=\$(lsof -i:9295 -t); kill -TERM \$pid || kill -KILL \$pid"
                } else {
                    bat "FOR /F \"tokens=5 delims= \" %%G IN (\"netstat -a | findstr :9295\") DO TaskKill.exe /PID %%G /fi \"memusage gt 0\""
                }

                withEnv(['JENKINS_NODE_COOKIE=dontkill']) {
                    if (isUnix()) {
                        sh 'nohup ./mvnw spring-boot:run -Dserver.port=9295 &'
                    } else {
                        bat 'start ./mvnw.cmd spring-boot:run -Dserver.port=9295'
                    }
                }
            }
        }
    }
}